export default {
  lightTheme: {
    background: "#F8F8FB",
    mainText: "#0C0E16",
    subText1: "#888EB0",
    subText2: "#7E88C3",
    invoiceBg: "#F8F8FB",
    headerBg: "#373B53",
    darkPurple: "#7C5DFA",
    lightPurple: "#9277FF",
    draft: "#373B53",
    pending: "#FF8F00",
    paid: "#33D69F",
    red: "#EC5757",
    ligthred: "#9277FF",
    checkBg: "#DFE3FA",
    black: "#141625",
    white: "#F8F8FB",
    //// FONTS
    fonts: {
      title: "League Spartan, sans-serif",
    },
    //BREAKPOINS
    breakpoints: {
      sm: "screen and (max-width: 640px)",
      mmd: "screen and (max-width: 750px)",
      md: "screen and (max-width: 886px)",
      lg: "screen and (max-width: 1024px)",
      xl: "screen and (max-width: 1280px)",
    },
  },
  darkTheme: {
    background: "#141625",
    mainText: "#F8F8FB",
    subText1: "#888EB0",
    subText2: "#DFE3FA",
    invoiceBg: "#1E2139",
    headerBg: "#1E2139",
    darkPurple: "#7C5DFA",
    lightPurple: "#9277FF",
    draft: "#DFE3FA",
    pending: "#FF8F00",
    paid: "#33D69F",
    red: "#EC5757",
    ligthred: "#9277FF",
    checkBg: "#DFE3FA",
    white: "#F8F8FB",
    fonts: {
      title: "League Spartan, sans-serif",
    },
    breakpoints: {
      sm: "screen and (max-width: 640px)",
      mmd: "screen and (max-width: 750px)",
      md: "screen and (max-width: 886px)",
      lg: "screen and (max-width: 1024px)",
      xl: "screen and (max-width: 1280px)",
    },
  },
}
